language: node_js
node_js:
  - "6"
  - "7"
  - "8"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.27.5
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn global add codecov
  - yarn install
script: 
  - yarn run test:coverage
  - codecov
