language: node_js
sudo: false
node_js:
  - "8"
  - "10"
install:
  - npm install -g codecov standard eslint eslint-plugin-ava
script:
  - yarn test:coverage
  - codecov
after_success:
  - yarn run semantic-release
