language: node_js
sudo: false
node_js:
  - "8"
  - "10"
install:
  - npm install -g codecov
script:
  - codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - yarn run semantic-release
